name: Deploy
on:
    workflow_dispatch

jobs: 
    jobs1:
        runs-on: ubuntu-latest
        steps: 
            - uses: azure/login@v1
              with:
                creds: ${{ secrets.AZUREPRINCIPAL }}
