name: Deploy to Azure
on:
    workflow_dispatch

jobs: 
    jobs1:
        runs-on: ubuntu-latest
        steps: 
            - name: Login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZUREPRINCIPAL }}

            # Deploy Bicep file
            - name: Deploy ARM Bicep Template
              uses: azure/arm-deploy@v1
              with:
                # subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                resourceGroupName: "${{ vars.AZURE_RG }}"
                template: ./InfrastructureAsCode/main.bicep
                parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
                failOnStdErr: false
