name: Manual workflow
on:
    workflow_dispatch:
    issues:
     types: [created]

jobs: 
    jobs1:
        runs-on: ubuntu-latest
        steps: 
            - name: Step 1
              run: echo "Executing step 1"

            - name: Step 2
              run: echo "Executing step 2"
    jobs2:
      runs-on: ubuntu-latest
      steps: 
          - name: Cowsays
            uses: mscoutermarsh/cowsays-action@v1
